import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: ["class"],
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        "primary": "#2563EB",
        "primary-container": "#DBEAFE",
        "on-primary-container": "#1E3A8A",
        "secondary": "#3B82F6",
        "secondary-container": "#EFF6FF",
        "tertiary": "#0EA5E9",
        "surface": "#F8FAFC",
        "surface-container-lowest": "#FFFFFF",
        "surface-container-low": "#F1F5F9",
        "surface-container-high": "#E2E8F0",
        "outline": "#64748B",
        "on-surface": "#0F172A",
        "on-surface-variant": "#334155",
        // Fallback aliases for unrefactored components
        "background": "#F8FAFC",
        "foreground": "#0F172A",
        "border": "#E2E8F0",
        "input": "#E2E8F0",
        "ring": "#2563EB",
        "card": "#FFFFFF",
        "card-foreground": "#0F172A",
        "muted": "#F1F5F9",
        "muted-foreground": "#334155",
        "accent": "#F1F5F9",
        "accent-foreground": "#0F172A",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        "sidebar-width": "16rem",
        "gutter-desktop": "1.5rem",
        "gutter-mobile": "1rem",
        "space-xs": "0.25rem",
        "space-2xl": "3rem",
        "space-sm": "0.5rem",
        "space-2xs": "0.125rem",
        "space-md": "0.75rem",
        "space-base": "1rem",
        "space-xl": "2rem",
        "space-3xl": "4rem",
        "max-content-width": "84rem",
        "space-lg": "1.5rem",
      },
      fontFamily: {
        "headline-md": ["var(--font-heading)", "Plus Jakarta Sans", "sans-serif"],
        "metric-num": ["var(--font-sans)", "Inter", "sans-serif"],
        "headline-lg-mobile": ["var(--font-heading)", "Plus Jakarta Sans", "sans-serif"],
        "body-lg": ["var(--font-sans)", "Inter", "sans-serif"],
        "headline-lg": ["var(--font-heading)", "Plus Jakarta Sans", "sans-serif"],
        display: ["var(--font-heading)", "Plus Jakarta Sans", "sans-serif"],
        "body-md": ["var(--font-sans)", "Inter", "sans-serif"],
        "body-sm": ["var(--font-sans)", "Inter", "sans-serif"],
        "label-md": ["var(--font-sans)", "Inter", "sans-serif"],
        "title-card": ["var(--font-heading)", "Plus Jakarta Sans", "sans-serif"],
        "label-sm": ["var(--font-sans)", "Inter", "sans-serif"],
        "headline-sm": ["var(--font-heading)", "Plus Jakarta Sans", "sans-serif"],
      },
      fontSize: {
        "headline-md": ["24px", { lineHeight: "32px", letterSpacing: "-0.02em", fontWeight: "600" }],
        "metric-num": ["28px", { lineHeight: "32px", letterSpacing: "-0.03em", fontWeight: "600" }],
        "headline-lg-mobile": ["26px", { lineHeight: "34px", letterSpacing: "-0.02em", fontWeight: "600" }],
        "body-lg": ["16px", { lineHeight: "26px", letterSpacing: "-0.01em", fontWeight: "400" }],
        "headline-lg": ["32px", { lineHeight: "40px", letterSpacing: "-0.025em", fontWeight: "600" }],
        display: ["48px", { lineHeight: "56px", letterSpacing: "-0.03em", fontWeight: "700" }],
        "body-md": ["14px", { lineHeight: "22px", letterSpacing: "-0.005em", fontWeight: "400" }],
        "body-sm": ["13px", { lineHeight: "18px", letterSpacing: "0em", fontWeight: "400" }],
        "label-md": ["13px", { lineHeight: "18px", letterSpacing: "0.005em", fontWeight: "500" }],
        "title-card": ["15px", { lineHeight: "22px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "label-sm": ["11px", { lineHeight: "16px", letterSpacing: "0.04em", fontWeight: "600" }],
        "headline-sm": ["18px", { lineHeight: "26px", letterSpacing: "-0.015em", fontWeight: "600" }],
      },
    },
  },
  plugins: [],
};

export default config;
