import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: ["class"],
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        "primary": "rgb(var(--primary-rgb) / <alpha-value>)",
        "primary-foreground": "rgb(var(--primary-foreground-rgb) / <alpha-value>)",
        "primary-hover": "var(--primary-hover)",
        "primary-container": "#DBEAFE",
        "on-primary-container": "#1E3A8A",
        "secondary": "rgb(var(--secondary-rgb) / <alpha-value>)",
        "secondary-foreground": "rgb(var(--secondary-foreground-rgb) / <alpha-value>)",
        "secondary-container": "#EFF6FF",
        "tertiary": "#0EA5E9",
        "surface": "rgb(var(--surface-rgb) / <alpha-value>)",
        "surface-container-lowest": "rgb(var(--surface-container-lowest-rgb) / <alpha-value>)",
        "surface-container-low": "rgb(var(--surface-container-low-rgb) / <alpha-value>)",
        "surface-container-high": "rgb(var(--surface-container-high-rgb) / <alpha-value>)",
        "outline": "#64748B",
        "on-surface": "rgb(var(--on-surface-rgb) / <alpha-value>)",
        "on-surface-variant": "rgb(var(--on-surface-variant-rgb) / <alpha-value>)",
        // Semantic theme variables
        "background": "rgb(var(--background-rgb) / <alpha-value>)",
        "foreground": "rgb(var(--foreground-rgb) / <alpha-value>)",
        "border": "rgb(var(--border-rgb) / <alpha-value>)",
        "input": "rgb(var(--input-rgb) / <alpha-value>)",
        "ring": "rgb(var(--ring-rgb) / <alpha-value>)",
        "card": "rgb(var(--card-rgb) / <alpha-value>)",
        "card-foreground": "rgb(var(--card-foreground-rgb) / <alpha-value>)",
        "muted": "rgb(var(--muted-rgb) / <alpha-value>)",
        "muted-foreground": "rgb(var(--muted-foreground-rgb) / <alpha-value>)",
        "accent": "rgb(var(--accent-rgb) / <alpha-value>)",
        "accent-foreground": "rgb(var(--accent-foreground-rgb) / <alpha-value>)",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        "sidebar-width": "16rem",
        "gutter-desktop": "1.5rem",
        "gutter-mobile": "1rem",
        "space-xs": "0.25rem",
        "space-2xl": "3rem",
        "space-sm": "0.5rem",
        "space-2xs": "0.125rem",
        "space-md": "0.75rem",
        "space-base": "1rem",
        "space-xl": "2rem",
        "space-3xl": "4rem",
        "max-content-width": "84rem",
        "space-lg": "1.5rem",
      },
      fontFamily: {
        "headline-md": ["var(--font-heading)", "Plus Jakarta Sans", "sans-serif"],
        "metric-num": ["var(--font-sans)", "Inter", "sans-serif"],
        "headline-lg-mobile": ["var(--font-heading)", "Plus Jakarta Sans", "sans-serif"],
        "body-lg": ["var(--font-sans)", "Inter", "sans-serif"],
        "headline-lg": ["var(--font-heading)", "Plus Jakarta Sans", "sans-serif"],
        display: ["var(--font-heading)", "Plus Jakarta Sans", "sans-serif"],
        "body-md": ["var(--font-sans)", "Inter", "sans-serif"],
        "body-sm": ["var(--font-sans)", "Inter", "sans-serif"],
        "label-md": ["var(--font-sans)", "Inter", "sans-serif"],
        "title-card": ["var(--font-heading)", "Plus Jakarta Sans", "sans-serif"],
        "label-sm": ["var(--font-sans)", "Inter", "sans-serif"],
        "headline-sm": ["var(--font-heading)", "Plus Jakarta Sans", "sans-serif"],
      },
      fontSize: {
        "headline-md": ["24px", { lineHeight: "32px", letterSpacing: "-0.02em", fontWeight: "600" }],
        "metric-num": ["28px", { lineHeight: "32px", letterSpacing: "-0.03em", fontWeight: "600" }],
        "headline-lg-mobile": ["26px", { lineHeight: "34px", letterSpacing: "-0.02em", fontWeight: "600" }],
        "body-lg": ["16px", { lineHeight: "26px", letterSpacing: "-0.01em", fontWeight: "400" }],
        "headline-lg": ["32px", { lineHeight: "40px", letterSpacing: "-0.025em", fontWeight: "600" }],
        display: ["48px", { lineHeight: "56px", letterSpacing: "-0.03em", fontWeight: "700" }],
        "body-md": ["14px", { lineHeight: "22px", letterSpacing: "-0.005em", fontWeight: "400" }],
        "body-sm": ["13px", { lineHeight: "18px", letterSpacing: "0em", fontWeight: "400" }],
        "label-md": ["13px", { lineHeight: "18px", letterSpacing: "0.005em", fontWeight: "500" }],
        "title-card": ["15px", { lineHeight: "22px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "label-sm": ["11px", { lineHeight: "16px", letterSpacing: "0.04em", fontWeight: "600" }],
        "headline-sm": ["18px", { lineHeight: "26px", letterSpacing: "-0.015em", fontWeight: "600" }],
      },
    },
  },
  plugins: [],
};

export default config;
